FROM openshift/origin-release:golang-1.14 AS builder

WORKDIR /tmp/kam
COPY . .
RUN go build  -mod=mod -o=out/kam cmd/kam/kam.go


FROM registry.redhat.io/rhel8/httpd-24

# Add application sources
COPY --from=builder /tmp/kam/out/kam /var/www/html/kam

# The run script uses standard ways to run the application
CMD run-httpd